<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
    <artifactId>process-engine-adapter-camunda-platform-c7-root</artifactId>
    <version>2026.09.3-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>process-engine-adapter-camunda-platform-c7-remote-testing</artifactId>
  <name>Camunda 7 Remote Testing Adapter</name>

  <properties>
    <process-engine-api-testing.version>2026.10.1</process-engine-api-testing.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>dev.bpm-crafters.process-engine-adapters</groupId>
      <artifactId>process-engine-adapter-camunda-platform-c7-remote-spring-boot-starter</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
      <artifactId>process-engine-api-testing-core</artifactId>
      <version>${process-engine-api-testing.version}</version>
    </dependency>
    <dependency>
      <groupId>io.holunda.c7</groupId>
      <artifactId>c7-rest-client-spring-boot-starter-feign</artifactId>
      <version>${c7.version}</version>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <version>${awaitility.version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jdk8</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-kotlin</artifactId>
    </dependency>

    <dependency>
      <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
      <artifactId>process-engine-api-testing-jgiven</artifactId>
      <version>${process-engine-api-testing.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>dev.bpm-crafters.process-engine-api-testing</groupId>
      <artifactId>process-engine-api-testing-contract</artifactId>
      <version>${process-engine-api-testing.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tngtech.jgiven</groupId>
      <artifactId>jgiven-junit5</artifactId>
      <version>${jgiven.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <testResources>
      <testResource>
        <directory>../c7-embedded-testing/src/test/resources</directory>
      </testResource>
    </testResources>
  </build>
</project>
